<?php
$title = 'Create a new game';
$this->headTitle($title);
?>

<!-- Bootstrap alert for the user notifications -->
<?php if (!empty($info)) : ?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong><?php echo $this->escapeHtml($info); ?></strong>
</div>
<?php endif; ?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Configuration of the form: add Bootstrap classes, id, content... -->
<?php
$form->setAttribute('action', $this->url('game', array('action' => 'new')));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('role', 'form');

$choiceContent = array();

foreach ($friends as $friend) {
	array_push($choiceContent, $friend->login);
}

/* The number of checkboxes depends on the friends count */
for ($i = 0; $i < count($choiceContent); $i++) {
	$checkbox = new Zend\Form\Element\Checkbox('choice' . $i);
	$checkbox->setUseHiddenElement(true);
	$checkbox->setCheckedValue($choiceContent[$i]);
	$checkbox->setAttribute('class', 'form-control');
	$checkbox->setAttribute('id', 'inputChoice' . $i);
	
	$form->add($checkbox);
}

$form->get('submit-new-game')->setAttribute('class', 'btn btn-default');

$form->prepare();
?>

<!-- Show new game form -->
<?php echo $this->form()->openTag($form); ?>
<?php for ($i = 0; $i < count($choiceContent); $i++) : ?>
<div class="form-group">
	<label for="inputChoice<?php echo $i; ?>" class="col-sm-2 control-label"><?php echo $choiceContent[$i]; ?></label>
	<div class="col-sm-1">
		<?php echo $this->formRow($form->get('choice' . $i)); ?>
	</div>
</div>
<?php endfor; ?>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?php echo $this->formSubmit($form->get('submit-new-game')); ?>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>