<form action="newgame">
    <table border="1" cellspacing="10">
        <thead>
            <tr>
                <th>Friends</th>
                <th>Add to game</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Jean</td>
                <td><input type="checkbox" name="Add" value="ON" checked="checked" /></td>
            </tr>
            <tr>
                <td>Paul</td>
                <td><input type="checkbox" name="Add" value="ON" checked="checked" /></td>
            </tr>
        </tbody>
    </table>
    <br/>
    <input type="submit" value="Launch game" name="newgame" />
</form>