<?php

$this->headTitle("Game");
?>

<!-- CSS -->
<style type="text/css">
	canvas
	{
		border: 1px solid black; /* We add a border */
		cursor : url(<?php echo $this->basePath('img/pencil.cur') ?>), pointer; /* When the cursor is over the drawing panel, we set it as a pencil */
	}
</style>

<!-- We include the jscolor library so we can easily get a color picker -->
<script type="text/javascript" src=<?php echo $this->basePath('js/jscolor.js') ?>></script>

<!-- Javascript -->
<script type="text/javascript" src=<?php echo $this->basePath('js/draw.js') ?>></script>

<script type="text/javascript">
	// Function that exports our canvas drawing as an image
	// It dosen't lay in the draw.js because we need some zend utilities
	function exportCanvasImage(){
		var dataURL = canvas.toDataURL();
		document.getElementById("canvasImage").src = dataURL;

		$.ajax({
			type: "POST",
			url: "<?php echo $this->basePath('savePicture.php')?>",
			data: { 
				imgBase64: dataURL,
				gameId: "<?php echo $gameId;?>"
			}
		}).done(function(o) {
			console.log('saved'); 
		});
	}
</script>

<?php switch ($_GET['test'] ):
	case 1: ?>
	
	En attente des autres joueurs</br>
	[list des joureurs]
	
<?php break;
    case 2:?>
	<div class="text-center">
		[Nom joueur] veut jouer avec vous !</br>
		<button type="button" class="btn btn-default btn-lg">
			<span class="glyphicon glyphicon-ok"></span>
		</button>
		<button type="button" class="btn btn-default btn-lg">
			<span class="glyphicon glyphicon-remove"></span>
		</button>
	</div>
	
<?php break;
    case 3:?>
	
	<div id="paintingEditor">
		Color : <input id="colorPicker" class="color" value="000000">
		<canvas id="myCanvas" width="800" height="600">
			Your browser does not support the HTML5 canvas tag.
		</canvas>
		<button id="exportButton" type="button">Export image</button>
	</div>

	<div id="rendingPanel"> 
		<img id="canvasImage">
	</div>

<?php break;
    case 4:?>
		<div class="row">
			<p class="text-center">Waiting on the painting ...</p>
		</div>
<?php break;
    case 5:?>
	
	<div class="text-center">
		[Proposition LIST][name] </br>
	</div>
	
	<img src="<?php echo file_get_contents('http://'.$_SERVER['HTTP_HOST'].$this->basePath().'/img/games/0') ?>"/>
	
<?php break;
    case 6:?>
	
	<div class="text-center">
		[input from zend]
		<button type="button" class="btn btn-default">suggest</button>
		
	</div>
	<img src="<?php echo file_get_contents('http://'.$_SERVER['HTTP_HOST'].$this->basePath().'/img/games/0') ?>"/>
	
<?php break;
    case 7:?>
	
	<div class="text-center">
	[list of all dudes with points]
	</div>
	
<?php endswitch; ?>

