<?php
$title = 'Play a game';
$this->headTitle($title);
?>

<?php if (!empty($info)) : ?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong><?php echo $this->escapeHtml($info); ?></strong>
</div>
<?php endif; ?>

<!-- We show page content only if there is no error -->
<?php if ($game_state != 0) : ?>

<h1><?php echo 'Game ' . $game_data['id']; ?></h1>

<!-- CSS -->
<style type="text/css">
	canvas
	{
		border: 1px solid black; /* We add a border */
		cursor : url(<?php echo $this->basePath('img/pencil.cur') ?>), pointer; /* When the cursor is over the drawing panel, we set it as a pencil */
	}
</style>

<!-- We include the jscolor library so we can easily get a color picker -->
<script type="text/javascript" src=<?php echo $this->basePath('js/jscolor.js') ?>></script>

<!-- Javascript -->
<script type="text/javascript" src=<?php echo $this->basePath('js/draw.js') ?>></script>

<script type="text/javascript">
	// Function that exports our canvas drawing as an image
	// It dosen't lay in the draw.js because we need some zend utilities
	function exportCanvasImage(){
		var dataURL = canvas.toDataURL();

		$.ajax({
			type: "POST",
			url: "<?php echo $this->basePath('savePicture.php')?>",
			data: { 
				imgBase64: dataURL,
				gameId: "<?php echo $game_data['id'];?>"
			}
		}).done(function(o) {
			console.log('saved'); 
		});
	}
</script>

<?php switch ($game_state):
	case 1: ?>
	
<?php
$form_accept_invitation->setAttribute('class', 'form-horizontal');
$form_accept_invitation->setAttribute('role', 'form');
$form_accept_invitation->setAttribute('action', $this->url('game', array('action' => 'play', 'id' => $game_data['id'])));

$form_accept_invitation->get('submit-accept-invitation')->setAttribute('class', 'btn btn-default');
$form_accept_invitation->get('submit-accept-invitation')->setAttribute('type', 'submit');

$form_accept_invitation->get('submit-decline-invitation')->setAttribute('class', 'btn btn-default');
$form_accept_invitation->get('submit-decline-invitation')->setAttribute('type', 'submit');

$form_accept_invitation->prepare();
?>

<?php echo $this->form()->openTag($form_accept_invitation); ?>
<div class="form-group">
	<div class="col-sm-3">
		<?php echo $this->escapeHtml($painter_data['login']) . ' wants to play with you!'; ?>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-3">
		<?php echo $this->formSubmit($form_accept_invitation->get('submit-accept-invitation')); ?>
		<?php echo $this->formSubmit($form_accept_invitation->get('submit-decline-invitation')); ?>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>
	
<?php break;
    case 2:?>
<div class="text-center">	
	<?php echo '<p>Some players still do not have accepted the game invitation. Time limit to accept: ' . $game_data['date_start'] . '.</p>'; ?>
</div>
<?php break;
    case 3:?>
<div class="text-center">	
	<?php echo 'You have to draw a "' . $mysterious_word . '".'; ?>
</div>
<div id="paintingEditor">
	Color : <input id="colorPicker" class="color" value="000000">
	<canvas id="myCanvas" width="500" height="500">
		Your browser does not support the HTML5 canvas tag.
	</canvas>
	<button id="exportButton" type="button">Save image</button>
</div>

<?php break;
    case 4:?>
<div class="text-center">	
	<?php echo '<p>' . $this->escapeHtml($painter_data['login']) . ' is still drawing. Come back at ' . $game_data['date_start'] . '.</p>'; ?>
</div>
<?php break;
    case 5:?>
	
<?php
$form_suggest_word->setAttribute('class', 'form-horizontal');
$form_suggest_word->setAttribute('role', 'form');
$form_suggest_word->setAttribute('action', $this->url('game', array('action' => 'play', 'id' => $game_data['id'])));

$form_suggest_word->get('word')->setAttribute('class', 'form-control');
$form_suggest_word->get('word')->setAttribute('type', 'text');
$form_suggest_word->get('word')->setAttribute('id', 'inputWord');

$form_suggest_word->get('submit-suggest-word')->setAttribute('class', 'btn btn-default');
$form_suggest_word->get('submit-suggest-word')->setAttribute('type', 'submit');

$form_suggest_word->prepare();
?>

<?php echo $this->form()->openTag($form_suggest_word); ?>
<div class="form-group">
	<div class="col-sm-3">
		<img src="<?php echo file_get_contents('http://'.$_SERVER['HTTP_HOST'].$this->basePath().'/img/games/'.$game_data['id']) ?>"/>
	</div>
</div>
<div class="form-group">
	<label for="inputWord" class="col-sm-2 control-label">What is this?</label>
	<div class="col-sm-3">
		<?php echo $this->formRow($form_suggest_word->get('word')); ?>
	</div>
	<div class="col-sm-6">
		<?php echo $this->formSubmit($form_suggest_word->get('submit-suggest-word')); ?>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>
	
<?php break;
    case 6:?>
<div class="text-center">	
	<?php echo '<p>Nobody guessed your image for the moment. Time limit to guess: ' . $game_data['date_find_limit'] . '.</p>'; ?>
</div>
<img src="<?php echo file_get_contents('http://'.$_SERVER['HTTP_HOST'].$this->basePath().'/img/games/'.$game_data['id']) ?>"/>
	
<?php break;
    case 7:?>
<div class="text-center">
	<?php echo '<p>This game is done.</p>'; ?>
</div>
<div class="text-left">
	<dl class="dl-horizontal col-md-offset-2">
		<?php for ($i = 0; $i < count($users_data); $i++) : ?>
		<dt><?php echo $users_data[$i]['login'] . ':'; ?></dt>
		<dd><?php echo $users_games_data[$i]['score'] . ' pts.'; ?></dd>
		<?php endfor; ?>
	</dl>
</div>
	
<?php endswitch; ?>
<?php endif; ?>
