<?php
$title = 'List of users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
<tr>
    <th>ID</th>
    <th>Login</th>
    <th>Password</th>
    <th>E-mail</th>
    <th>Date de création</th>
    <th>Date dernière connexion</th>
    <th>Activé</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->id);?></td>
    <td><?php echo $this->escapeHtml($user->login);?></td>
    <td><?php echo $this->escapeHtml($user->password);?></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td><?php echo $this->escapeHtml($user->date_creation);?></td>
    <td><?php echo $this->escapeHtml($user->date_last_connection);?></td>
    <td><?php echo $this->escapeHtml($user->activated);?></td>
</tr>
<?php endforeach; ?>
</table>