<?php 
	echo $this->doctype(); 
	use Zend\Session\Container;
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icon-hearc-color.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
					<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/ps-logo.png') ?>" alt="Paint something logo"/>&nbsp;<?php echo $this->translate('Paint Something') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
						<?php
							$nm_authInfo = new Container('authentification_info');
							if(!isset($nm_authInfo->login)):
						?>
						
							<li class="active"><a href="<?php echo $this->url('home', array('action' => 'signin')) ?>"><?php echo $this->translate('Sign-in') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('home', array('action' => 'signup')) ?>"><?php echo $this->translate('Sign-up') ?></a></li>
						
						<?php else: ?>  
							<li class="active"><a href="<?php echo $this->url('members-list') ?>"><?php echo $this->translate('Members list') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('member', array('name' => $nm_authInfo->login,
																							  'action' => 'games')) ?>"><?php echo $this->translate('My Games') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('game', array('action' => 'new')) ?>"><?php echo $this->translate('New game') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('member', array('name' => $nm_authInfo->login)) ?>"><?php echo $this->translate('Profile') ?></a></li>
							<li class="active"><a href="<?php echo $this->url('home', array('action' => 'logout')) ?>"><?php echo $this->translate('Logout') ?></a></li>
						<?php endif; ?>
						<li class="active"><a href="<?php echo $this->url('home', array('action' => 'about')) ?>"><?php echo $this->translate('About') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><?php echo date('Y')?> HE-ARC <?php echo $this->translate('Web application') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
