<?php
$title = 'List of users';
$this->headTitle($title);
?>

<div class="text-center">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
</div>
<table class="table">
    <tr>
        <th>Username</th>
        <th>E-mail</th>
        <th>Account creation</th>
        <th>Last connection</th>
        <th></th>
    </tr>
<?php foreach ($users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->login);?></td>
        <td><?php echo $this->escapeHtml($user->email);?></td>
        <td><?php echo $this->escapeHtml($user->date_creation);?></td>
        <td><?php echo $this->escapeHtml($user->date_last_connection);?></td>
        <td><a href="<?php echo $this->url('member', array('name' => $this->escapeHtml($user->login)));?>">More...</a></td>
    </tr>
<?php endforeach; ?>
</table>