<?php
$user = $users->current();
$title =  'Edit ' . $user->login . "'s profile";
$this->headTitle($title);
?>
<?php if (!empty($info)) : ?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong><?php echo $this->escapeHtml($info); ?></strong>
</div>
<?php endif; ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('member', array('name' => $this->escapeHtml($user->login), 'action' => 'edit')));
$form->get('email')->setValue($this->escapeHtml($user->email));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="col-md-4">
		<dl class="dl-horizontal">
			<dt>Email</dt>
			<dd><?php echo $this->formRow($form->get('email')); ?></dd>
			<dt>New password</dt>
			<dd><?php echo $this->formRow($form->get('new-password')); ?></dd>
			<dt>Confirm password</dt>
			<dd><?php echo $this->formRow($form->get('confirm-password')); ?></dd>
		</dl>
		<div class="row">
			<?php echo $this->formSubmit($form->get('submit-edit-member')); ?>
			<a class="btn btn-link" href="<?php echo $this->url('member', array('name' => $this->escapeHtml($user->login)));?>">Cancel</a>
		</div>
	</div>
</div>
<?php
echo $this->form()->closeTag();
?>