<?php
$user = $users->current();
$title =  'Edit ' . $user->login . "'s profile";
$this->headTitle($title);
?>

<div class="row">
	<div class="col-md-4">
		<dl class="dl-horizontal">
			<dt>Login</dt>
			<dd><?php echo $user->login; ?></dd>
			<dt>E-mail</dt>
			<dd><?php echo $user->email; ?></dd>
			<dt>Old password</dt>
			<dd>[FORM PASSWORD]</dd>
			<dt>Password</dt>
			<dd>[FORM PASSWORD]</dd>
			<dt>Confirm password</dt>
			<dd>[FORM PASSWORD]</dd>
		</dl>
	</div>
	<div class="col-md-8">
		<div class="row">
			<a class="btn btn-link" href="<?php echo $this->url('member', array('name' => $this->escapeHtml($user->login)));?>">Save changes</a>
		</div>
		<div class="row">
			<a class="btn btn-link" href="<?php echo $this->url('member', array('name' => $this->escapeHtml($user->login)));?>">Cancel</a>
		</div>
	</div>
</div>

<!--<form action="edit">
    
    Login : <input type="text" name="login" value="Michel" /><br/><br/>
    Password : <input type="password" name="password" value="pass123" /><br/><br/>
    PasswordComfirm : <input type="password" name="password_comfirm" value="pass123" /><br/><br/>
    E-mail : <input type="text" name="email" value="michel.dupond@gmail.com" /><br/><br/>

    <input type="submit" value="Save changes" />
    <input type="reset" value="Cancel" />

</form>-->