<?php
$title = 'List of friends';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
    <tr>
        <th>Username</th>
        <th>E-mail</th>
        <th>Last connection</th>
        <th></th>
    </tr>
<?php foreach ($friends as $friend) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($friend->login);?></td>
        <td><?php echo $this->escapeHtml($friend->email);?></td>
        <td><?php echo $this->escapeHtml($friend->date_last_connection);?></td>
        <td><a href="<?php echo $this->url('member', array('name' => $this->escapeHtml($friend->login)));?>">More...</a></td>
    </tr>
<?php endforeach; ?>
</table>