<?php
$title = 'List of ' . $login . '\'s friends';
$this->headTitle($title);
?>
<?php if (!empty($info)) : ?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong><?php echo $this->escapeHtml($info); ?></strong>
</div>
<?php endif; ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('member', array('name' => $login, 'action' => 'friends')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo $this->formSubmit($form->get('submit-add-friend'));
echo $this->form()->closeTag();
?>
<table class="table">
    <tr>
        <th>Username</th>
        <th>E-mail</th>
        <th>Last connection</th>
        <th></th>
    </tr>
<?php foreach ($friends as $friend) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($friend->login);?></td>
        <td><?php echo $this->escapeHtml($friend->email);?></td>
        <td><?php echo $this->escapeHtml($friend->date_last_connection);?></td>
        <td><a href="<?php echo $this->url('member', array('name' => $this->escapeHtml($friend->login)));?>">More...</a></td>
    </tr>
<?php endforeach; ?>
</table>