<h1>My Games</h1>
<h2>Running</h2>
<table cellpadding="10">
    <tbody>
        <tr>
            <td>Youplaboum</td>
        </tr>
        <tr>
            <td>I have no idea what I'm doing</td>
        </tr>
        <tr>
            <td>Grumfff</td>
        </tr>
    </tbody>
</table>

<h2>Terminated</h2>

<table cellpadding="10">
    <tbody>
        <tr>
            <td>OldLady</td>
        </tr>
        <tr>
            <td>Schtroumpf</td>
        </tr>
        <tr>
            <td>SuperGame</td>
        </tr>
    </tbody>
</table>