<?php
$user = $users->current();
$title =  $user->login . "'s profile";
$this->headTitle($title);
?>

<div class="col-md-offset-2">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
</div>

<div class="row">
	<div class="col-md-4">
		<dl class="dl-horizontal">
			<dt>Username</dt>
			<dd><?php echo $user->login; ?></dd>
			<dt>Email</dt>
			<dd><?php echo $user->email; ?></dd>
			<dt>Last connection</dt>
			<dd><?php echo $user->date_last_connection; ?></dd>
			<dt>Inscription date</dt>
			<dd><?php echo $user->date_creation; ?></dd>
		</dl>
	</div>
	<div class="col-md-8">
		<div class="row">
			<a class="btn btn-link" href="<?php echo $this->url('member', array('name' => $this->escapeHtml($user->login), 'action' => 'edit'));?>">Edit</a>
		</div>
		<div class="row">
			<a class="btn btn-link" href="<?php echo $this->url('member', array('name' => $this->escapeHtml($user->login), 'action' => 'friends'));?>">Friends</a>
		</div>
		<div class="row">
			<a class="btn btn-link" href="<?php echo $this->url('member', array('name' => $this->escapeHtml($user->login), 'action' => 'games'));?>">Games</a>
		</div>
	</div>
</div>