<div class="row">
	<div class="col-md-4">
		<dl class="dl-horizontal">
			<dt>Username</dt>
			<dd>[USERNAME]</dd>
			<dt>Email</dt>
			<dd>[EMAIL]</dd>
			<dt>Last connection</dt>
			<dd>[LAST CONNECTION]</dd>
			<dt>Inscription date</dt>
			<dd>[INSCREPTION DATE]</dd>
		</dl>
	</div>
	<div class="col-md-8">
		<div class="row">
		<button type="button" class="btn btn-link">Edit</button>
		</div>
		<div class="row">
		<button type="button" class="btn btn-link">Friends</button>
		</div>
		<div class="row">
		<button type="button" class="btn btn-link">Games</button>
		</div>
	</div>
</div>