<div class="alert alert-success">
	<div class="progress progress-striped active">
		<div class="progress-bar"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
		</div>
	</div>
	<dl class="dl-horizontal col-md-offset-2">
		<dt>Supervisor</dt>
		<dd>D. Grunenwald</dd>
		<dt>Students</dt>
		<dd>E. Frank, D. Jupille, M. Nasuti</dd>
		<dt>Purpose</dt>
		<dd>"Paint Something!" is a school project. The goal is to make a website with Zend Framework 2.</dd>
		<dt></dt>
		<dd></dd>
	</dl>
		<div class="progress progress-striped active">
			<div class="progress-bar"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
		</div>
	</div>
</div>