<div class="text-center">
	<h2>Paint Something!</h2>
	
	PS is a draw guessing game. Play it with your friends and have fun!
	
	<h2>Join us!</h2>
	
	Go on the "signup" tab or click on the this awsome <a class="btn btn-info" href="<?php echo $this->url('home', array('action' => 'signup')); ?>">link</a>!
	
	<h2>How to play!</h2>
	
	<ol class="text-left col-md-offset-3">
		<li> First step, signup on the site. </li>
		<li> Add friends wich you can find in the member list. </li>
		<li> Then start a game. You can choose all the people who are friend with you. </li>
		<li> At the begining you draw a something and propose it to your firends. </li>
		<li> Your friends have to guess the word and you can see wich one they are trying. </li>
		<li> When a game is over, one of the guessing player goes the drawer. </li>
		<li> Now it's your turn to guess! </li>
	</ol>

</div>