<?php
$title = 'Sign in';
$this->headTitle($title);
?>

<?php if (!empty($info)) : ?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong><?php echo $this->escapeHtml($info); ?></strong>
</div>
<?php endif; ?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('home', array('action' => 'signin')));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('role', 'form');

$form->get('login')->setAttribute('class', 'form-control');
$form->get('login')->setAttribute('id', 'inputLogin');
$form->get('login')->setAttribute('placeholder', 'Username');

$form->get('password')->setAttribute('class', 'form-control');
$form->get('password')->setAttribute('id', 'inputPassword');
$form->get('password')->setAttribute('placeholder', 'Password');

$form->get('submit-sign-in')->setAttribute('class', 'btn btn-default');

$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
	<label for="inputLogin" class="col-sm-2 control-label">Login</label>
	<div class="col-sm-3">
		<?php echo $this->formRow($form->get('login')); ?>
	</div>
</div>
<div class="form-group">
	<label for="inputPassword" class="col-sm-2 control-label">Password</label>
	<div class="col-sm-3">
		<?php echo $this->formRow($form->get('password')); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?php echo $this->formSubmit($form->get('submit-sign-in')); ?>
		<a class="btn btn-link" href="<?php echo $this->url('home', array('action' => 'signup'));?>">Not signed up? Come join us!</a>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>