<?php
$title = 'Sign in';
$this->headTitle($title);
?>
<form class="form-horizontal" role="form">
	<div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">Login</label>
		<div class="col-sm-3">
			<input type="email" class="form-control" id="inputEmail3" placeholder="Email or Username">
		</div>
    </div>
    <div class="form-group">
		<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
		<div class="col-sm-3">
			<input type="password" class="form-control" id="inputPassword3" placeholder="Password">
		</div>
    </div>
    <div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Sign in</button>
		</div>
    </div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="button" class="btn btn-link">Not signed up ? Come join us !</button>
		</div>
	</div>
</form>